const APP_CATALOG = Object.freeze([
  // AI and development tools
  { pattern: /^chatgpt$/i, displayName: 'ChatGPT' },
  { pattern: /^codex$/i, displayName: 'Codex' },
  { pattern: /^cursor$/i, displayName: 'Cursor' },
  { pattern: /^(?:code|code-insiders)$/i, displayName: 'VS Code' },
  { pattern: /^visual studio code(?: - insiders)?$/i, displayName: 'VS Code' },
  { pattern: /^zed$/i, displayName: 'Zed' },
  { pattern: /^xcode$/i, displayName: 'Xcode' },
  { pattern: /^(?:intellij idea|idea64?)$/i, displayName: 'IntelliJ IDEA' },
  { pattern: /^pycharm(?:64)?$/i, displayName: 'PyCharm' },
  { pattern: /^webstorm(?:64)?$/i, displayName: 'WebStorm' },
  { pattern: /^phpstorm(?:64)?$/i, displayName: 'PhpStorm' },
  { pattern: /^sublime text$/i, displayName: 'Sublime Text' },
  { pattern: /^atom$/i, displayName: 'Atom' },
  { pattern: /^vim$/i, displayName: 'Vim' },
  { pattern: /^emacs$/i, displayName: 'Emacs' },

  // Terminals
  { pattern: /^warp$/i, displayName: 'Warp' },
  { pattern: /^iterm2?$/i, displayName: 'iTerm' },
  { pattern: /^terminal$/i, displayName: 'Terminal' },
  { pattern: /^ghostty$/i, displayName: 'Ghostty' },
  { pattern: /^hyper$/i, displayName: 'Hyper' },
  { pattern: /^(?:windows terminal|windowsterminal)$/i, displayName: 'Windows Terminal' },

  // Creative tools
  { pattern: /^(?:adobe )?photoshop/i, displayName: 'Adobe Photoshop' },
  { pattern: /^(?:adobe )?illustrator/i, displayName: 'Adobe Illustrator' },
  { pattern: /^adobe after effects/i, displayName: 'Adobe After Effects' },
  { pattern: /^(?:adobe premiere pro|adobe premiere)/i, displayName: 'Adobe Premiere Pro' },
  { pattern: /^adobe lightroom/i, displayName: 'Adobe Lightroom' },
  { pattern: /^adobe indesign/i, displayName: 'Adobe InDesign' },
  { pattern: /^adobe acrobat/i, displayName: 'Adobe Acrobat' },
  { pattern: /^adobe bridge/i, displayName: 'Adobe Bridge' },
  { pattern: /^adobe audition/i, displayName: 'Adobe Audition' },
  { pattern: /^figma$/i, displayName: 'Figma' },
  { pattern: /^sketch$/i, displayName: 'Sketch' },
  { pattern: /^canva$/i, displayName: 'Canva' },
  { pattern: /^affinity designer(?: 2)?$/i, displayName: 'Affinity Designer' },
  { pattern: /^affinity photo(?: 2)?$/i, displayName: 'Affinity Photo' },
  { pattern: /^affinity publisher(?: 2)?$/i, displayName: 'Affinity Publisher' },
  { pattern: /^final cut pro$/i, displayName: 'Final Cut Pro' },
  { pattern: /^logic pro$/i, displayName: 'Logic Pro' },
  { pattern: /^pro tools$/i, displayName: 'Pro Tools' },
  { pattern: /^blender$/i, displayName: 'Blender' },
  { pattern: /^cinema 4d$/i, displayName: 'Cinema 4D' },
  { pattern: /^maya$/i, displayName: 'Maya' },
  { pattern: /^3ds max$/i, displayName: '3ds Max' },

  // Office and productivity
  { pattern: /^(?:microsoft word|winword)$/i, displayName: 'Microsoft Word' },
  { pattern: /^(?:microsoft excel|excel)$/i, displayName: 'Microsoft Excel' },
  { pattern: /^(?:microsoft powerpoint|powerpnt)$/i, displayName: 'Microsoft PowerPoint' },
  { pattern: /^(?:microsoft outlook|outlook)$/i, displayName: 'Microsoft Outlook' },
  { pattern: /^microsoft project$/i, displayName: 'Microsoft Project' },
  { pattern: /^microsoft visio$/i, displayName: 'Microsoft Visio' },
  { pattern: /^notion$/i, displayName: 'Notion' },
  { pattern: /^notion calendar$/i, displayName: 'Notion Calendar' },
  { pattern: /^obsidian$/i, displayName: 'Obsidian' },
  { pattern: /^roam research$/i, displayName: 'Roam Research' },
  { pattern: /^logseq$/i, displayName: 'Logseq' },
  { pattern: /^keynote$/i, displayName: 'Keynote' },
  { pattern: /^pages$/i, displayName: 'Pages' },
  { pattern: /^numbers$/i, displayName: 'Numbers' },

  // Browsers
  { pattern: /^(?:google chrome|google-chrome(?:-stable)?)$/i, displayName: 'Google Chrome' },
  { pattern: /^chrome$/i, displayName: 'Chrome' },
  { pattern: /^safari$/i, displayName: 'Safari' },
  { pattern: /^firefox$/i, displayName: 'Firefox' },
  { pattern: /^(?:microsoft edge|msedge)$/i, displayName: 'Microsoft Edge' },
  { pattern: /^(?:brave browser|brave-browser|brave)$/i, displayName: 'Brave Browser' },
  { pattern: /^opera$/i, displayName: 'Opera' },
  { pattern: /^arc$/i, displayName: 'Arc' },

  // Database and API tools
  { pattern: /^tableplus$/i, displayName: 'TablePlus' },
  { pattern: /^sequel pro$/i, displayName: 'Sequel Pro' },
  { pattern: /^navicat$/i, displayName: 'Navicat' },
  { pattern: /^dbeaver$/i, displayName: 'DBeaver' },
  { pattern: /^postman$/i, displayName: 'Postman' },
  { pattern: /^insomnia$/i, displayName: 'Insomnia' },
  { pattern: /^paw$/i, displayName: 'Paw' },

  // Engineering software
  { pattern: /^autocad$/i, displayName: 'AutoCAD' },
  { pattern: /^solidworks$/i, displayName: 'SolidWorks' },
  { pattern: /^fusion 360$/i, displayName: 'Fusion 360' },
  { pattern: /^unity$/i, displayName: 'Unity' },
  { pattern: /^unreal engine$/i, displayName: 'Unreal Engine' },
  { pattern: /^godot$/i, displayName: 'Godot' },
  { pattern: /^docker desktop$/i, displayName: 'Docker Desktop' },
  { pattern: /^vmware fusion$/i, displayName: 'VMware Fusion' },
  { pattern: /^parallels desktop$/i, displayName: 'Parallels Desktop' },
  { pattern: /^wireshark$/i, displayName: 'Wireshark' },
  { pattern: /^charles$/i, displayName: 'Charles' },
  { pattern: /^sourcetree$/i, displayName: 'Sourcetree' },
  { pattern: /^(?:github desktop|githubdesktop)$/i, displayName: 'GitHub Desktop' },
  { pattern: /^gitkraken$/i, displayName: 'GitKraken' }
]);

module.exports = APP_CATALOG;
